import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Score } from '../api/types';
import { Card, EmptyState, formatValue } from './ui';

const COLORS = ['#34d399', '#60a5fa', '#fbbf24', '#fb7185', '#a78bfa', '#22d3ee'];
export function CategoryChart({ score }: { score?: Score }) {
  const rows = Object.entries(score?.category_scores || {}).map(([name, row]) => ({ name: name.replace(/_/g, ' '), score: row.score, findings: row.finding_count }));
  return <Card title="Category security" eyebrow="ASSESSED"><div className="chart-wrap">{rows.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={rows} margin={{ top: 8, right: 8, left: -22, bottom: 4 }}><CartesianGrid stroke="#1c2937" vertical={false}/><XAxis dataKey="name" tick={{ fill: '#718096', fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis domain={[0, 100]} tick={{ fill: '#718096', fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background: '#101923', border: '1px solid #263445', borderRadius: 10, color: '#e7edf5' }} formatter={(v) => [`${formatValue(v)} / 100`, 'Score']}/><Bar dataKey="score" radius={[5, 5, 0, 0]}>{rows.map((row, i) => <Cell key={row.name} fill={COLORS[i % COLORS.length]}/>)}</Bar></BarChart></ResponsiveContainer> : <EmptyState title="No scored categories" description="A category appears after the backend assesses a relevant control."/>}</div></Card>;
}
export function ProbabilityChart({ probabilities }: { probabilities?: Record<string, number | null> }) {
  const rows = Object.entries(probabilities || {}).filter(([, value]) => value != null).map(([name, value]) => ({ name, probability: Number(value) * 100 })).sort((a,b) => b.probability-a.probability);
  return <div className="mini-chart">{rows.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={rows} layout="vertical" margin={{ top: 0, right: 16, left: 6, bottom: 0 }}><XAxis type="number" domain={[0, 100]} hide/><YAxis type="category" dataKey="name" width={92} tick={{ fill: '#9aa9ba', fontSize: 10 }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background: '#101923', border: '1px solid #263445', borderRadius: 10, color: '#e7edf5' }} formatter={(v) => [`${formatValue(v)}%`, 'Probability']}/><Bar dataKey="probability" radius={[0, 4, 4, 0]}>{rows.map((r,i)=><Cell key={r.name} fill={COLORS[i%COLORS.length]}/>)}</Bar></BarChart></ResponsiveContainer> : <div className="chart-empty">Class probabilities not available.</div>}</div>;
}
export function ShapChart({ features }: { features?: Array<{ feature?: string; shap_value?: number | null }> }) {
  const rows = (features || []).filter((f) => f.shap_value != null).map((f) => ({ name: f.feature || 'Unknown', contribution: Number(f.shap_value) })).sort((a,b) => Math.abs(b.contribution)-Math.abs(a.contribution));
  return <div className="mini-chart shap-chart">{rows.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={rows} layout="vertical" margin={{ top: 0, right: 12, left: 8, bottom: 0 }}><CartesianGrid stroke="#1c2937" horizontal={false}/><XAxis type="number" tick={{ fill: '#718096', fontSize: 10 }} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="name" width={128} tick={{ fill: '#9aa9ba', fontSize: 10 }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background: '#101923', border: '1px solid #263445', borderRadius: 10, color: '#e7edf5' }} formatter={(v) => [formatValue(v), 'SHAP contribution']}/><Bar dataKey="contribution" radius={[0, 4, 4, 0]}>{rows.map((r)=><Cell key={r.name} fill={r.contribution >= 0 ? '#34d399' : '#fb7185'}/>)}</Bar></BarChart></ResponsiveContainer> : <div className="chart-empty">SHAP explanation not available.</div>}</div>;
}
