import { AlertOctagon, CheckCheck, FileSearch, Info } from 'lucide-react';
import type { AnalysisResponse, Finding } from '../api/types';
import { Card, EmptyState, formatValue, ProvenanceBadge, SectionTitle, StatusIcon, Tag } from '../components/ui';

const severityTone = (severity?: string): 'green'|'amber'|'red'|'default' => { const s=severity?.toLowerCase(); if(s==='critical'||s==='high') return 'red'; if(s==='medium') return 'amber'; if(s==='low') return 'green'; return 'default'; };
export function AssessmentPage({ data }: { data: AnalysisResponse | null }) {
 const assessment=data?.assessment; const score=data?.score; const findings=assessment?.findings||[]; const metadataFindings=findings.filter(item=>item.category?.toLowerCase()==='metadata_exposure'||item.rule_id?.startsWith('IPSEC-META-')); const cryptoFindings=findings.filter(item=>!metadataFindings.includes(item)); const coverage=assessment?.coverage; const metadataControl=assessment?.controls?.find(control=>control.control_id==='IPSEC-META-001');
 return <div className="page-stack"><SectionTitle eyebrow="DETERMINISTIC SECURITY CONCLUSIONS" title="Security assessment" description="Rule based findings and controls grounded in observed protocol evidence."/>
  <div className="assessment-overview"><div className="assessment-score"><div className="score-ring" style={{'--score': `${score?.score ?? 0}%`} as React.CSSProperties}><div><strong>{score?.score == null ? 'N/A' : formatValue(score.score)}</strong><small>/ 100</small></div></div><div><div className="eyebrow">SECURITY SCORE</div><h2>{score?.risk_level || 'NOT ASSESSED'}</h2><p>This score reflects assessed controls in the available evidence; it is not a universal VPN security claim.</p></div></div><div className="assessment-metric"><span>SCORING COVERAGE</span><strong>{score?.scoring_coverage == null ? 'N/A' : `${formatValue(score.scoring_coverage)}%`}</strong><div className="progress-track"><div style={{width:`${Math.max(0,Math.min(100,score?.scoring_coverage||0))}%`}}/></div><small>Category weight represented in this score</small></div><div className="assessment-metric"><span>ASSESSMENT COVERAGE</span><strong>{coverage?.percentage == null ? 'N/A' : `${formatValue(coverage.percentage)}%`}</strong><div className="progress-track"><div className="progress-green" style={{width:`${Math.max(0,Math.min(100,coverage?.percentage||0))}%`}}/></div><small>{formatValue(coverage?.assessed, 'N/A')} of {formatValue(coverage?.total_applicable, 'N/A')} applicable controls · {formatValue(score?.assessed_control_count, 'N/A')} scored controls</small></div></div>
  <Card title="Security controls" eyebrow="CONTROL ASSESSMENT" action={<span className="subtle-count">{formatValue(assessment?.controls?.length, '0')} controls</span>}>
   {assessment?.controls?.length ? <div className="control-list">{assessment.controls.map((control,i)=><div className="control-row" key={control.control_id||i}><StatusIcon status={control.status}/><div className="control-content"><div className="control-title"><strong>{formatValue(control.name)}</strong><span className="control-id">{formatValue(control.control_id)}</span></div><p>{formatValue(control.reason, 'Not assessed')}</p>{!!control.evidence_refs?.length&&<div className="ref-list">Evidence refs: {control.evidence_refs.join(' · ')}</div>}</div><Tag tone={control.status==='ASSESSED'?'green':control.status==='NOT_APPLICABLE'?'default':'amber'}>{formatValue(control.status, 'NOT_ASSESSED')}</Tag></div>)}</div> : <EmptyState title="No controls returned" description="Control status has not been assessed for this capture."/>}
  </Card>
  <Card title="Findings" eyebrow="RULE ENGINE RESULTS" action={<span className="finding-count"><AlertOctagon size={14}/>{formatValue(assessment?.finding_count, '0')} total</span>}>
   {cryptoFindings.length ? <div className="finding-list">{cryptoFindings.map((finding,index)=><FindingCard finding={finding} key={finding.rule_id||index}/>)}</div> : <EmptyState title={data ? 'No cryptographic findings' : 'Awaiting analysis'} description={data ? 'No cryptographic rule findings were returned for the available evidence.' : 'Analyze a PCAP to evaluate the applicable security rules.'}/>}
  </Card>
  <Card title="Metadata exposure" eyebrow="SEPARATE CONTROL ASSESSMENT" action={<Tag tone={metadataControl?.status==='ASSESSED'?'green':'amber'}>{formatValue(metadataControl?.status, 'NOT_ASSESSED')}</Tag>}>
   <p className="metadata-control-summary">{formatValue(metadataControl?.reason, 'Metadata exposure control status was not returned.')}</p>
   {metadataFindings.length ? <div className="finding-list">{metadataFindings.map((finding,index)=><FindingCard finding={finding} key={finding.rule_id||index}/>)}</div> : <EmptyState title="No metadata exposure findings" description="No metadata exposure finding was returned by the assessment rules."/>}
  </Card>
  <Card title="Observed evidence" eyebrow="ASSESSMENT INPUTS"><div className="table-scroll"><table><thead><tr><th>Evidence field</th><th>Value</th><th>Source</th><th>Provenance</th></tr></thead><tbody>{assessment?.observations?.length ? assessment.observations.map((item,index)=><tr key={index}><td className="mono">{formatValue(item.field)}</td><td>{formatValue(item.value, 'Not observed')}</td><td>{formatValue(item.source)}</td><td><ProvenanceBadge value={item.provenance}/></td></tr>) : <tr><td colSpan={4} className="table-empty">{data ? 'No observations returned.' : 'No evidence loaded.'}</td></tr>}</tbody></table></div><div className="notice"><Info size={14}/> NOT_ASSESSED controls are insufficient evidence, not failed controls.</div></Card>
 </div>;
}
function FindingCard({finding}: {finding: Finding}) { return <article className="finding-card"><div className="finding-top"><span className="finding-symbol"><FileSearch size={16}/></span><div className="finding-title"><strong>{formatValue(finding.name)}</strong><small>{formatValue(finding.rule_id)}</small></div><Tag tone={severityTone(finding.severity)}>{formatValue(finding.severity, 'N/A')}</Tag><Tag>{formatValue(finding.category, 'N/A')}</Tag><ProvenanceBadge value={finding.provenance}/></div><p>{formatValue(finding.description, 'No description returned.')}</p><div className="finding-detail-grid"><div><span>Recommendation</span><p>{formatValue(finding.recommendation, 'N/A')}</p></div><div><span>Evidence</span><p className="mono">{formatValue(finding.evidence?.field)} = {formatValue(finding.evidence?.value, 'Not observed')}</p></div></div><div className="finding-footer"><span><CheckCheck size={13}/> {formatValue(finding.category, 'Uncategorized')}</span><span>Conclusion assessed by deterministic rules</span></div></article>; }
