import { ArrowDownLeft, ArrowUpRight, KeyRound, Radio, Shield, Waypoints } from 'lucide-react';
import type { AnalysisResponse } from '../api/types';
import { Card, EmptyState, formatValue, ProvenanceBadge, SectionTitle, Tag } from '../components/ui';

export function IPsecIntelligence({ data }: { data: AnalysisResponse | null }) {
 const ike=data?.ike; const esp=data?.esp; const proposal=ike?.selected_proposal;
 return <div className="page-stack"><SectionTitle eyebrow="PROTOCOL EVIDENCE" title="IPsec intelligence" description="Packet-level IKE and ESP observations extracted from the analyzed capture."/>
  <div className="grid-two">
   <Card title="IKE security association" eyebrow="IKE" action={<Tag tone={ike?.observed ? 'green' : 'amber'}>{ike?.observed ? 'OBSERVED' : 'NOT OBSERVED'}</Tag>}>
    {ike?.observed ? <><div className="protocol-hero"><div className="protocol-mark"><Radio size={22}/></div><div><strong>{formatValue(ike.version, 'Not observed')}</strong><small>Internet Key Exchange</small></div><ProvenanceBadge value="OBSERVED"/></div><div className="key-value-grid"><div><span>Exchanges</span><strong>{formatValue(ike.exchanges?.length, 'Not observed')}</strong></div><div><span>Selected proposal</span><strong>{proposal ? `Frame ${formatValue(proposal.frame)}` : 'Not observed'}</strong></div><div><span>Encryption</span><strong>{formatValue(proposal?.encryption, 'Not observed')}</strong></div><div><span>PRF</span><strong>{formatValue(proposal?.prf, 'Not observed')}</strong></div><div><span>Integrity</span><strong>{formatValue(proposal?.integrity, 'Not observed')}</strong></div><div><span>DH group</span><strong>{formatValue(proposal?.dh_group, 'Not observed')}</strong></div></div><div className="evidence-box"><div className="eyebrow">IKE EVIDENCE</div>{(ike.evidence||[]).map((item,i)=><div className="evidence-line" key={i}><span>{formatValue(item.type)} protocol evidence</span><span>{formatValue(item.source)}</span><ProvenanceBadge value={item.provenance}/></div>)}</div></> : <EmptyState title="No IKE observed" description="The analyzed capture did not contain directly observable IKE exchanges."/>}
   </Card>
   <Card title="ESP data plane" eyebrow="ESP" action={<Tag tone={esp?.observed ? 'green' : 'amber'}>{esp?.observed ? 'OBSERVED' : 'NOT OBSERVED'}</Tag>}>
    {esp?.observed ? <><div className="protocol-hero"><div className="protocol-mark protocol-mark-blue"><Shield size={22}/></div><div><strong>{formatValue(esp.packet_count)} <small>packets</small></strong><small>Encapsulating Security Payload</small></div><ProvenanceBadge value="OBSERVED"/></div><div className="sequence-note"><KeyRound size={15}/><span>{esp.sequence_analysis?.note || (esp.sequence_analysis?.observed ? 'Sequence numbers observed.' : 'Sequence information not observed.')}</span></div><div className="direction-list">{(esp.directions||[]).map((direction,index)=><div className="direction-row" key={index}><span className="direction-icon">{index%2===0?<ArrowUpRight size={15}/>:<ArrowDownLeft size={15}/>}</span><span className="direction-endpoints"><strong>{formatValue(direction.source, 'Not observed')}</strong><span>→</span><strong>{formatValue(direction.destination, 'Not observed')}</strong><small>SPI {formatValue(direction.spi, 'N/A')}</small></span><span className="direction-sequences"><strong>{formatValue(direction.packet_count)}</strong><small>packets · seq {formatValue(direction.first_sequence)} → {formatValue(direction.last_sequence)}</small></span></div>)}</div><div className="evidence-box"><div className="eyebrow">PROTOCOL EVIDENCE</div>{(esp.evidence||[]).map((item,i)=><div className="evidence-line" key={i}><span>{formatValue(item.type)} packet evidence</span><span>{formatValue(item.source)}</span><ProvenanceBadge value={item.provenance}/></div>)}</div></> : <EmptyState title="No ESP observed" description="The capture contains no ESP packets available to this analyzer."/>}
   </Card>
  </div>
  <Card title="IKE exchanges" eyebrow="OBSERVED EXCHANGE SEQUENCE" action={<span className="subtle-count">{formatValue(ike?.exchanges?.length, '0')} entries</span>}>
   {ike?.exchanges?.length ? <div className="table-scroll"><table><thead><tr><th>Frame</th><th>Exchange type</th><th>Version</th><th>Source</th><th>Destination</th><th>Provenance</th></tr></thead><tbody>{ike.exchanges.map((exchange,index)=><tr key={index}><td className="mono">{formatValue(exchange.frame)}</td><td><span className="exchange-name"><Waypoints size={14}/>{formatValue(exchange.exchange_type)}</span></td><td>{formatValue(exchange.version, 'Not observed')}</td><td className="mono">{formatValue(exchange.source, 'Not observed')}</td><td className="mono">{formatValue(exchange.destination, 'Not observed')}</td><td><ProvenanceBadge value={exchange.provenance}/></td></tr>)}</tbody></table></div> : <EmptyState title="No exchanges to show" description="Exchange details will appear when IKE packets are observed."/>}
  </Card>
 </div>;
}
