import { useState } from 'react';
import { Archive, Download, FileText, LoaderCircle, ServerCog, ShieldCheck } from 'lucide-react';
import { Card, SectionTitle, Tag, ErrorBanner, formatValue } from '../components/ui';
import { generateReport, type ReportType } from '../api/client';
import type { AnalysisResponse } from '../api/types';

type ReportsPageProps = { data: AnalysisResponse | null; file: File | null };

export function ReportsPage({ data, file }: ReportsPageProps) {
  const [loading, setLoading] = useState<ReportType | null>(null);
  const [error, setError] = useState('');
  const analysisReady = Boolean(data && file);
  const downloadReport = async (reportType: ReportType) => {
    if (!file || loading) { if (!file) setError('Analyze a PCAP first before generating a report.'); return; }
    setLoading(reportType); setError('');
    try {
      const result = await generateReport(file, reportType);
      const url = URL.createObjectURL(result.blob);
      const anchor = document.createElement('a'); anchor.href = url; anchor.download = result.filename;
      document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url);
    } catch (err) { setError(err instanceof Error ? err.message : 'Report generation failed.'); }
    finally { setLoading(null); }
  };
  const coverage = data?.assessment?.coverage;
  const reports = [
    { type: 'executive' as const, label: 'EXECUTIVE REPORT', title: 'Security assessment summary', icon: <ShieldCheck size={25}/>, description: 'A concise summary of security posture, key findings, IPsec evidence, traffic intelligence, and assessment coverage.', features: [{ icon: <ShieldCheck size={16}/>, title: 'Evidence first', copy: 'Observed, inferred, and assessed results stay clearly distinguished.' }, { icon: <Archive size={16}/>, title: 'Coverage context', copy: 'Score, risk, findings, and evaluated control coverage.' }], button: 'Download Executive PDF' },
    { type: 'technical' as const, label: 'TECHNICAL REPORT', title: 'Detailed technical evidence', icon: <FileText size={25}/>, description: 'Detailed IKE and ESP evidence, controls, findings, score breakdown, traffic features, SHAP explanations, and metadata exposure.', features: [{ icon: <FileText size={16}/>, title: 'Protocol evidence', copy: 'IKE, ESP, selected proposal, and packet-level evidence.' }, { icon: <ShieldCheck size={16}/>, title: 'Explainable AI', copy: 'Traffic predictions include confidence and SHAP contributions.' }], button: 'Download Technical PDF' },
  ];
  return <div className="page-stack">
    <SectionTitle eyebrow="REPORTING" title="Reports" description="Generate evidence-backed PDF reports from the analyzed IPsec capture." action={<Tag>{analysisReady ? 'ANALYSIS READY' : 'ANALYSIS REQUIRED'}</Tag>}/>
    {error && <ErrorBanner message={error}/>}
    <Card className="report-context" title="Report evidence" eyebrow="CURRENT ANALYSIS" action={<Tag tone="blue">SERVER GENERATED</Tag>}>
      <div className="report-context-grid">
        <div><span>ANALYZED PCAP</span><strong>{formatValue(file?.name, 'No PCAP analyzed')}</strong></div>
        <div><span>ASSESSMENT COVERAGE</span><strong>{coverage?.percentage == null ? 'N/A' : `${formatValue(coverage.percentage)}%`}</strong><small>{formatValue(coverage?.assessed, '0')} of {formatValue(coverage?.total_applicable, '0')} applicable controls assessed</small></div>
        <div><span>SCORING COVERAGE</span><strong>{data?.score?.scoring_coverage == null ? 'N/A' : `${formatValue(data.score.scoring_coverage)}%`}</strong><small>Weighted categories represented in score</small></div>
      </div>
      <div className="notice"><ServerCog size={15}/> PDFs are generated by the backend from server-side analysis of this capture; report evidence is re-evaluated during generation.</div>
    </Card>
    <div className="report-cards">{reports.map(report => <Card key={report.type} className="report-card">
      <div className="report-card-heading"><div className="report-icon">{report.icon}</div><div><div className="eyebrow">{report.label}</div><h2>{report.title}</h2></div></div>
      <p className="report-description">{report.description}</p>
      <div className="report-card-features">{report.features.map(feature => <div key={feature.title}>{feature.icon}<span><strong>{feature.title}</strong><small>{feature.copy}</small></span></div>)}</div>
      <button className="button button-primary" onClick={() => downloadReport(report.type)} disabled={!analysisReady || loading !== null}>
        {loading === report.type ? <><LoaderCircle size={16} className="spinner"/>Generating…</> : <><Download size={16}/>{report.button}</>}
      </button>
    </Card>)}</div>
  </div>;
}
