import { ArrowDownUp, Bot, ChevronDown, Clock3, Gauge, Layers, Network, RadioTower, ShieldAlert } from 'lucide-react';
import { useState } from 'react';
import type { AnalysisResponse, TrafficFlow } from '../api/types';
import { ProbabilityChart, ShapChart } from '../components/Charts';
import { Card, EmptyState, formatBytes, formatValue, ProvenanceBadge, SectionTitle, Tag } from '../components/ui';

export function TrafficIntelligence({data}: {data: AnalysisResponse|null}) { const flows=data?.traffic_intelligence?.flows||[];
 return <div className="page-stack"><SectionTitle eyebrow="AI-ASSISTED METADATA-BASED TRAFFIC INFERENCE" title="Traffic intelligence" description="Per-flow behavior features, model predictions and metadata exposure assessments." action={<Tag tone="blue">INFERRED CLASS · ASSESSED EXPOSURE</Tag>}/>
 <div className="privacy-banner"><Bot size={18}/><span><strong>Encrypted traffic remains encrypted.</strong> Classification uses encrypted-flow metadata. Protected payload content is not decrypted.</span></div>
 {!flows.length ? <Card>{<EmptyState title={data ? 'No traffic flows returned' : 'No analysis loaded'} description={data ? 'No valid ESP endpoint flows were available for traffic inference.' : 'Analyze a PCAP to explore traffic metadata and model outputs.'}/>}</Card> : flows.map((flow,index)=><FlowCard flow={flow} index={index} key={`${flow.features?.flow_source}-${flow.features?.flow_destination}-${index}`}/>)}</div>
}
function Metric({icon,label,value,detail}: {icon: React.ReactNode; label:string; value:string; detail?:string}) { return <div className="flow-metric"><span className="flow-metric-icon">{icon}</span><div><small>{label}</small><strong>{value}</strong>{detail&&<em>{detail}</em>}</div></div>; }
function FlowCard({flow,index}: {flow: TrafficFlow;index:number}) { const [open,setOpen]=useState(true); const f=flow.features||{}; const classification=flow.classification; const explanation=classification?.explanation; const metadata=flow.metadata_exposure;
 const directional = f.direction_ratio == null ? 'N/A' : `${formatValue(f.direction_ratio*100)}% forward`;
 return <Card className="flow-card" title={`Flow ${String(index+1).padStart(2,'0')}`} eyebrow="OBSERVED ESP ENDPOINT FLOW" action={<button className="icon-button" aria-label={open?'Collapse flow':'Expand flow'} onClick={()=>setOpen(!open)}><ChevronDown className={open?'':'rotate-180'} size={17}/></button>}>
 <div className="flow-endpoint-bar"><div><span>SOURCE</span><strong>{formatValue(f.flow_source, 'Not observed')}</strong></div><ArrowDownUp size={17}/><div><span>DESTINATION</span><strong>{formatValue(f.flow_destination, 'Not observed')}</strong></div><div className="flow-provenance"><ProvenanceBadge value="OBSERVED"/></div></div>
 {open&&<><div className="flow-metrics-grid"><Metric icon={<Layers size={15}/>} label="PACKETS" value={formatValue(f.packet_count)}/><Metric icon={<RadioTower size={15}/>} label="TOTAL BYTES" value={formatBytes(f.total_bytes)}/><Metric icon={<Clock3 size={15}/>} label="DURATION" value={f.flow_duration==null?'N/A':`${formatValue(f.flow_duration)} s`}/><Metric icon={<Gauge size={15}/>} label="PACKETS / SEC" value={formatValue(f.packets_per_second)}/><Metric icon={<Network size={15}/>} label="BYTES / SEC" value={formatBytes(f.bytes_per_second)+'/s'}/><Metric icon={<ArrowDownUp size={15}/>} label="DIRECTION RATIO" value={directional} detail={`${formatValue(f.forward_packet_count)} fwd · ${formatValue(f.reverse_packet_count)} rev`}/><Metric icon={<Layers size={15}/>} label="BURST COUNT" value={formatValue(f.burst_count)}/><Metric icon={<ShieldAlert size={15}/>} label="METADATA EXPOSURE" value={formatValue(metadata?.overall_exposure, 'Not assessed')} detail={`${formatValue(metadata?.finding_count,'0')} findings`}/></div>
 <div className="flow-ai-grid"><div className="flow-ai-summary"><div className="eyebrow"><Bot size={13}/> AI TRAFFIC CLASS</div><div className="predicted-class">{formatValue(classification?.predicted_class)}</div><div className="prediction-meta"><span>{classification?.confidence==null?'N/A':`${formatValue(classification.confidence*100)}%`} confidence</span><ProvenanceBadge value={classification?.provenance}/></div><div className="model-info"><span>Model version<strong>{formatValue(classification?.model_version)}</strong></span><span>Model type<strong>{formatValue(classification?.model_type)}</strong></span></div></div>
 <div className="flow-chart-panel"><div className="chart-panel-title">CLASS PROBABILITIES <ProvenanceBadge value={classification?.provenance}/></div><ProbabilityChart probabilities={classification?.class_probabilities}/></div></div>
 <div className="flow-ai-grid shap-grid"><div className="flow-chart-panel"><div className="why-prediction-heading"><div><div className="eyebrow">EXPLAINABLE AI</div><strong>Why this prediction?</strong></div><ProvenanceBadge value={explanation?.provenance || classification?.provenance}/></div><div className="prediction-explanation-meta"><span>Predicted class <strong>{formatValue(classification?.predicted_class)}</strong></span><span>Confidence <strong>{classification?.confidence==null?'N/A':`${formatValue(classification.confidence*100)}%`}</strong></span><span>Model version <strong>{formatValue(classification?.model_version)}</strong></span><span>Explanation method <strong>{formatValue(explanation?.explanation_method, 'SHAP / TreeExplainer')}</strong></span></div><div className="chart-panel-title">SHAP FEATURE CONTRIBUTIONS</div><ShapChart features={explanation?.top_features}/><div className="chart-legend"><span><i className="legend-positive"/> Supports prediction</span><span><i className="legend-negative"/> Opposes prediction</span></div></div><div className="top-features-panel"><div className="chart-panel-title">TOP CONTRIBUTING FEATURES</div>{explanation?.top_features?.length ? explanation.top_features.map((feature,i)=><div className="feature-contribution" key={feature.feature||i}><span className="feature-rank">{i+1}</span><span className="feature-name">{formatValue(feature.feature)}</span><span className="feature-value">{formatValue(feature.value)}</span><span className={`feature-impact ${feature.direction==='supports'?'impact-positive':'impact-negative'}`}>{feature.direction||'N/A'}</span><strong className={Number(feature.shap_value)>=0?'text-green':'text-red'}>{feature.shap_value==null?'N/A':`${Number(feature.shap_value)>0?'+':''}${formatValue(feature.shap_value)}`}</strong></div>):<EmptyState title="No SHAP features" description="Feature contribution details were not returned."/>}</div></div>
 <div className="metadata-findings"><div className="metadata-head"><div><div className="eyebrow">METADATA EXPOSURE FINDINGS</div><p>{formatValue(metadata?.summary, 'Not assessed')}</p></div><ProvenanceBadge value={metadata?.provenance}/></div>{metadata?.findings?.length ? <div className="metadata-findings-grid">{metadata.findings.map((finding,i)=><article key={i} className="metadata-finding"><div><strong>{formatValue(finding.feature)}</strong><Tag tone={finding.exposure_level==='HIGH'?'red':finding.exposure_level==='MEDIUM'?'amber':'green'}>{formatValue(finding.exposure_level)}</Tag></div><p>{formatValue(finding.explanation)}</p><div className="metadata-potential">Potential inference: {formatValue(finding.potential_inference)}</div><p className="metadata-recommendation"><strong>Recommendation</strong>{formatValue(finding.recommendation)}</p><div className="observed-value"><span>Observed value</span><code>{typeof finding.observed_value==='object'&&finding.observed_value!==null?JSON.stringify(finding.observed_value):formatValue(finding.observed_value)}</code><ProvenanceBadge value={finding.provenance}/></div></article>)}</div> : <div className="metadata-no-findings">No metadata findings returned for this flow.</div>}</div>
 </>}
 </Card>;
}
