import { useRef, useState } from 'react';
import type { ChangeEvent, DragEvent } from 'react';
import { BarChart3, ChevronDown, CircleHelp, CloudUpload, FileCheck2, FileUp, FlaskConical, Gauge, Hexagon, LockKeyhole, Menu, Network, Radio, ScanLine, ShieldCheck, X } from 'lucide-react';
import { analyzePcap } from './api/client';
import type { AnalysisResponse } from './api/types';
import { Dashboard } from './pages/Dashboard';
import { IPsecIntelligence } from './pages/IPsecIntelligence';
import { AssessmentPage } from './pages/Assessment';
import { TrafficIntelligence } from './pages/TrafficIntelligence';
import { ReportsPage } from './pages/Reports';
import { SimulationPage } from './pages/Simulation';
import { ErrorBanner, formatValue } from './components/ui';

type Page='Dashboard'|'IPsec Intelligence'|'Security Assessment'|'Traffic Intelligence'|'Reports'|'What-if Simulation';
const navItems: Array<{name:Page; icon:typeof Gauge; group:string}>=[{name:'Dashboard',icon:Gauge,group:'WORKSPACE'},{name:'IPsec Intelligence',icon:Radio,group:'ANALYSIS'},{name:'Security Assessment',icon:ShieldCheck,group:'ANALYSIS'},{name:'Traffic Intelligence',icon:Network,group:'ANALYSIS'},{name:'Reports',icon:BarChart3,group:'MANAGE'},{name:'What-if Simulation',icon:FlaskConical,group:'MANAGE'}];
const validExtensions=['.pcap','.pcapng','.cap'];
export default function App() {
 const [page,setPage]=useState<Page>('Dashboard'); const [data,setData]=useState<AnalysisResponse|null>(null); const [file,setFile]=useState<File|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [dragging,setDragging]=useState(false); const [uploadOpen,setUploadOpen]=useState(false); const [mobileNav,setMobileNav]=useState(false); const input=useRef<HTMLInputElement>(null);
 const pick=(candidate?:File)=>{if(!candidate)return;const ext=candidate.name.slice(candidate.name.lastIndexOf('.')).toLowerCase();setError(validExtensions.includes(ext)?'':`Invalid file type. Expected .pcap, .pcapng, or .cap. Selected: ${candidate.name}`);setFile(validExtensions.includes(ext)?candidate:null);};
 const analyze=async()=>{if(!file){setError('Choose a .pcap, .pcapng, or .cap file first.');return;}setLoading(true);setError('');try{const result=await analyzePcap(file);setData(result);setUploadOpen(false);setPage('Dashboard');}catch(e){setError(e instanceof Error?e.message:'PCAP analysis failed.');}finally{setLoading(false);}};
 const reset=()=>{setFile(null);setData(null);setError('');if(input.current)input.current.value='';};
 const onDrop=(event:DragEvent<HTMLDivElement>)=>{event.preventDefault();setDragging(false);pick(event.dataTransfer.files[0]);};
 const onFileChange=(event:ChangeEvent<HTMLInputElement>)=>pick(event.target.files?.[0]);
 const pageContent=()=>{switch(page){case 'Dashboard':return <Dashboard data={data} onAnalyze={()=>setUploadOpen(true)}/>;case 'IPsec Intelligence':return <IPsecIntelligence data={data}/>;case 'Security Assessment':return <AssessmentPage data={data}/>;case 'Traffic Intelligence':return <TrafficIntelligence data={data}/>;case 'Reports':return <ReportsPage/>;case 'What-if Simulation':return <SimulationPage data={data}/>;}};
 return <div className="app-shell"><aside className={`sidebar ${mobileNav?'sidebar-open':''}`}><div className="brand"><div className="brand-mark"><Hexagon size={22}/><span/></div><div><strong>SENTINEL</strong><small>IPSEC INTELLIGENCE</small></div><button className="mobile-close" onClick={()=>setMobileNav(false)} aria-label="Close navigation"><X size={18}/></button></div><div className="workspace-switch"><div className="workspace-avatar">S</div><div><strong>Security workspace</strong><small>Personal environment</small></div><ChevronDown size={14}/></div><nav className="nav-list">{navItems.map((item,index)=><div key={item.name}>{(index===0||navItems[index-1].group!==item.group)&&<div className="nav-label">{item.group}</div>}<button className={`nav-item ${page===item.name?'nav-active':''}`} onClick={()=>{setPage(item.name);setMobileNav(false);}}><item.icon size={17}/><span>{item.name}</span>{page===item.name&&<i/>}</button></div>)}</nav><div className="sidebar-bottom"><div className="api-health"><span className={`health-dot ${data?'health-ready':''}`}/><span><strong>{data?'Analysis ready':'API connection'}</strong><small>{data?'Latest capture loaded':'Connects on analysis'}</small></span><CircleHelp size={14}/></div><div className="sidebar-user"><div className="user-avatar">SI</div><div><strong>SIH 26160</strong><small>Security analyst</small></div><span className="user-menu">•••</span></div></div></aside>
 <div className="main-column"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobileNav(true)} aria-label="Open navigation"><Menu size={19}/></button><div className="breadcrumb"><span>Workspace</span><span>/</span><strong>{page}</strong></div><div className="topbar-actions"><div className="environment-pill"><span/> LOCAL ENVIRONMENT</div><button className="button button-outline button-small" onClick={()=>setUploadOpen(true)}><FileUp size={15}/> Analyze PCAP</button><div className="top-avatar">SI</div></div></header><main className="main-content">{pageContent()}</main><footer className="footer"><span>Sentinel IPsec Intelligence <span className="footer-separator">·</span> SIH 26160</span><span>OBSERVED <i/> INFERRED <i/> ASSESSED <i/> NOT ASSESSED</span></footer></div>
 {uploadOpen&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!loading)setUploadOpen(false);}}><div className="upload-modal"><header className="modal-header"><div><div className="eyebrow">PCAP ANALYZER</div><h2>Analyze a capture</h2><p>Upload a network capture to begin protocol and traffic analysis.</p></div><button className="icon-button" onClick={()=>setUploadOpen(false)} aria-label="Close" disabled={loading}><X size={18}/></button></header><div className={`dropzone ${dragging?'dropzone-active':''} ${file?'dropzone-selected':''}`} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={onDrop} onClick={()=>input.current?.click()} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')input.current?.click();}}><input ref={input} type="file" accept=".pcap,.pcapng,.cap,application/vnd.tcpdump.pcap,application/x-pcapng" onChange={onFileChange}/>{file?<><div className="drop-icon drop-icon-selected"><FileCheck2 size={23}/></div><strong>{file.name}</strong><span>{formatValue(file.size)} bytes · ready to analyze</span><button className="text-button" onClick={e=>{e.stopPropagation();reset();}}>Remove file</button></>:<><div className="drop-icon"><CloudUpload size={24}/></div><strong>Drop your PCAP file here</strong><span>or <button className="text-button" type="button">browse files</button> from your device</span><small>Supported formats: .pcap, .pcapng, .cap</small></>}</div>{error&&<ErrorBanner message={error} onRetry={file?analyze:undefined}/>}<div className="upload-guidance"><LockKeyhole size={14}/><span>Capture is sent to the configured analysis backend for processing.</span></div><div className="modal-actions"><button className="button button-quiet" onClick={()=>{reset();setUploadOpen(false);}}>Reset</button><button className="button button-primary" onClick={analyze} disabled={loading||!file}>{loading?<><span className="spinner"/>Analyzing capture…</>:<><ScanLine size={16}/> Upload & analyze</>}</button></div></div></div>}
 </div>;
}
