config setup
    uniqueids=no

conn vpn-a-to-vpn-b
    keyexchange=ikev2
    authby=psk

    left=10.10.10.1
    leftid=@vpn-a
    leftsubnet=10.10.10.1/32

    right=10.10.10.2
    rightid=@vpn-b
    rightsubnet=10.10.10.2/32

    ike=aes256gcm16-prfsha256-modp2048
    esp=aes256gcm16-modp2048

    dpdaction=restart
    dpddelay=30s

    keyingtries=%forever

    auto=start
