charon {
    load_modular = yes

    plugins {
        include /etc/strongswan.d/charon/*.conf

        stroke {
            socket = unix:///var/run/charon.ctl
            secrets_file = /etc/ipsec.secrets
        }
    }
}
